# -*- coding: utf-8 -*-
"""smart Waste classfication

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jzseSKvVrZUszjWOXY2Uq25EZb0kgvF
"""

!pip install tensorflow

!pip install -q streamlit
!npm install -g localtunnel

import tensorflow as tf
import numpy as np
import cv2
import os
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split

from google.colab import files
uploaded = files.upload()

import zipfile
with zipfile.ZipFile('dataset (1).zip', 'r') as zip_ref:
    zip_ref.extractall('dataset')

classes = ['plastic','paper','glass','metal','trash']
img_size = 224
data = []
labels = []

for idx, cls in enumerate(classes):
    path = os.path.join('dataset', 'Garbage classification', 'Garbage classification', cls)
    for img_name in os.listdir(path):
        try:
            img_path = os.path.join(path, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (img_size, img_size))
            data.append(img)
            label = [0]*len(classes)
            label[idx] = 1
            labels.append(label)
        except:
            pass

data = np.array(data) / 255.0
labels = np.array(labels)
print(data.shape, labels.shape)

os.listdir('dataset/Garbage classification/Garbage classification')

os.listdir('dataset/Garbage classification')

os.listdir('dataset')

X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2)

model = models.Sequential([
 layers.Conv2D(32,(3,3),activation='relu',input_shape=(224,224,3)),
 layers.MaxPooling2D(2,2),
 layers.Conv2D(64,(3,3),activation='relu'),
 layers.MaxPooling2D(2,2),
 layers.Conv2D(128,(3,3),activation='relu'),
 layers.MaxPooling2D(2,2),
 layers.Flatten(),
 layers.Dense(128,activation='relu'),
 layers.Dense(len(classes), activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=5)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.legend(['Train','Validation'])
plt.show()

model.save('garbage_model.h5')

import matplotlib.pyplot as plt
import numpy as np

# Get a mapping from one-hot encoded labels back to class names
label_to_class = {tuple(label): cls for label, cls in zip(np.eye(len(classes)), classes)}

plt.figure(figsize=(10, 10))
for i in range(9):
    idx = np.random.randint(0, len(data)) # Pick a random image index
    plt.subplot(3, 3, i + 1)
    plt.imshow(data[idx])
    # Convert one-hot encoded label back to class name
    current_label = labels[idx]
    class_name = classes[np.argmax(current_label)]
    plt.title(class_name)
    plt.axis('off')
plt.suptitle('Sample Images from the Dataset', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()